environment:

  matrix:
    # node.js
    - nodejs_version: "6"

install:
# Get latest stable version of nodejs
- ps: Install-Product node $env:nodejs_version
- npm install

# Post-install test scripts.
test_script:
# Output useful debugging infos
- node --version
- npm --version
# run tests
- npm test

# Dont actually build
build: off
